apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-rs
  labels:
    run: app
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - name: app-rs
        image: nginx
